-- CreateTable
CREATE TABLE `User` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `SENHA` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `User_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Tarefa` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TITULO` VARCHAR(191) NOT NULL,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL,
    `DTCADASTRO` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
